Repository FRONTENDSCHOOL10/Code12hour, pull requests merged in 2024-07, with the labels that each got.

#12 feature : 로그인, 회원가입 페이지 마크업
  src/assets/icons/input/isChecked=false.svg
  src/assets/icons/input/isChecked=true.svg
  src/assets/icons/input/isSelected=false.svg
  src/assets/icons/input/isSelected=true.svg
  src/pages/login/index.html
  src/pages/login/login.js
  src/pages/login/login.scss
  src/pages/register/index.html
  src/pages/register/register.js
  src/pages/register/register.scss
Labels: 🎨 Html&css

#16 feat: 메인 페이지 마크업 및 슬라이드 기능 구현
  index.html
  src/assets/icons/arrow/list-arrow.svg
  src/assets/icons/arrow/swiper-next.svg
  src/assets/icons/arrow/swiper-prev.svg
  src/assets/icons/arrow/view-all.svg
  src/assets/icons/product-list/Cart.svg
  src/assets/icons/product-list/reviews.svg
  src/assets/images/banner/1.jpg
  src/assets/images/banner/line-banner01.png
  src/main.js
  src/main.scss
Labels: ✨ Feature, 🎨 Html&css

#15 feat: product-detail 페이지 마크업
  src/assets/icons/product-detail/Bell.svg
  src/assets/icons/product-detail/Frame.svg
  src/assets/icons/product-detail/Frame2.svg
  src/assets/icons/product-detail/Frame3.svg
  src/assets/icons/product-detail/Frame4.svg
  src/assets/icons/product-detail/Frame5.svg
  src/assets/icons/product-detail/Heart.svg
  src/assets/icons/product-detail/Minus.svg
  src/assets/icons/product-detail/Plus.svg
  src/assets/icons/product-detail/noti.svg
  src/assets/images/product-detail/product01-information.png
  src/assets/images/product-detail/product01-point.png
  src/assets/images/product-detail/product01-wide.png
  src/assets/images/product-detail/product01.png
  src/components/header/header.js
  src/components/header/header.scss
  src/components/header/index.html
  src/pages/product-detail/index.html
  src/pages/product-detail/product-detail.scss
  src/styles/base/_reset.scss
Labels: 🎨 Html&css

#20 refactor: 메인 페이지 콘텐츠 구조 개선 및 미사용 클래스 제거
  index.html
Labels: 🔨 Refactor

#13 feat: 상품 디테일: 상품 후기 마크업
  src/assets/icons/review/helpful.svg
  src/assets/icons/review/paging.svg
  src/assets/icons/review/review-empty.svg
  src/pages/product-review/index.html
  src/pages/product-review/product-review.js
  src/pages/product-review/product-review.scss
Labels: 🎨 Html&css

#22 feat: product-cart 페이지 마크업
  src/assets/icons/product-cart/Arrow.svg
  src/assets/icons/product-cart/Cold.svg
  src/assets/icons/product-cart/Frozen.svg
  src/assets/icons/product-cart/Location.svg
  src/assets/icons/product-cart/Temperature.svg
  src/components/header/header.js
  src/pages/product-cart/index.html
  src/pages/product-cart/product-cart.js
  src/pages/product-cart/product-cart.scss
Labels: 🎨 Html&css

#24 Chore: vite build 환경 수정
  src/components/footer/footer.js
  src/components/header/header.js
  src/components/header/header.scss
  vite.config.js
Labels: ⚙ Setting

#25 feat: 최근 본 상품 컴포넌트 마크업
  src/components/recent-product/index.html
  src/components/recent-product/recent-product.js
  src/components/recent-product/recent-product.scss
Labels: 🎨 Html&css

#26 feat: 상품 목록 페이지 마크업
  src/assets/icons/arrow/pagination-1.png
  src/assets/icons/arrow/pagination-2.png
  src/assets/icons/product-list/info.svg
  src/pages/product-list/index.html
  src/pages/product-list/product-list.js
  src/pages/product-list/product-list.scss
Labels: 🎨 Html&css

#31 feat: 모달 컴포넌트 마크업 및 스타일링
  public/assets/icons/modal/close-btn.svg
  src/assets/images/modal/Frame 134.png
  src/components/modal/index.html
  src/components/modal/modal.js
  src/components/modal/modal.scss
Labels: 🎨 Html&css

#21 feature: 상품 리스트 사이드 필터 패널 마크업
  public/assets/icons/arrow/Arrow_down.svg
  public/assets/icons/arrow/Arrow_up.svg
  src/components/side-filter-panel/index.html
  src/components/side-filter-panel/side-filter-panel.js
  src/components/side-filter-panel/side-filter-panel.scss
  src/styles/abstracts/_mixins.scss
Labels: 🎨 Html&css

#38 refactor: 문의, 후기, 모달 컴포넌트 관련 웹접근성 점검
  public/assets/icons/product-inquiry/Answer.svg
  public/assets/icons/product-inquiry/Private.svg
  public/assets/icons/product-inquiry/Question.svg
  src/components/modal/index.html
  src/components/modal/modal.scss
  src/pages/product-inquiry/index.html
  src/pages/product-inquiry/product-inquiry.scss
  src/pages/product-review/index.html
  src/pages/product-review/product-review.scss
Labels: 🔨 Refactor, 🥰 Accessibility

#41 refactor: 유지보수 및 기능구현을 위한 마크업, 스타일링 리팩토링
  src/components/modal/index.html
  src/components/modal/modal.scss
  src/pages/product-inquiry/index.html
  src/pages/product-inquiry/product-inquiry.scss
  src/pages/product-review/index.html
  src/pages/product-review/product-review.scss
Labels: 🔨 Refactor, 🥰 Accessibility

#34 feat: 광고 팝업창 구현
  index.html
  public/assets/images/ad-popup/ad-popup.webp
  src/components/ad-popup/ad-popup.js
  src/components/ad-popup/ad-popup.scss
  src/components/ad-popup/index.html
  src/components/index.js
  src/main.js
Labels: 🎨 Html&css

#44 refactor: 로그인 회원가입 scss 리팩토링
  src/pages/login/login.scss
  src/pages/register/index.html
  src/pages/register/register.scss
Labels: 🔨 Refactor

#45 modify: 최근 본 상품 마크업 및 스타일링 수정
  index.html
  public/assets/icons/arrow/recent-arrow.svg
  src/assets/images/banner/1.webp
  src/components/index.js
  src/components/recent-product/index.html
  src/components/recent-product/recent-product.js
  src/components/recent-product/recent-product.scss
  src/main.js
Labels: 🔨 Refactor

#48 feature: 상품 후기 기능 구현
  src/components/modal/index.html
  src/components/modal/modal.scss
  src/pages/product-review/index.html
  src/pages/product-review/product-review.js
  src/pages/product-review/product-review.scss
Labels: ✨ Feature

#50 feat: 메인 페이지 장바구니 버튼 클릭 시 모달창 띄우기
  index.html
  src/components/cart-button/cart-button.js
  src/components/cart-button/cart-button.scss
  src/components/cart-button/index.html
  src/components/index.js
  src/main.js
Labels: ✨ Feature, 🎨 Html&css

#51 refactor: 헤더 컴포넌트 접근성 점검
  src/components/header/header.js
  src/components/header/header.scss
  src/components/header/index.html
  src/components/index.js
  src/components/product-review/index.html
  src/components/product-review/product-review.js
  src/components/product-review/product-review.scss
  src/pages/product-detail/index.html
  src/pages/product-detail/product-detail.js
  src/pages/product-review/product-review.js
Labels: 🔨 Refactor

#52 feature: 상품 문의 기능 구현
  src/pages/product-inquiry/index.html
  src/pages/product-inquiry/product-inquiry.js
Labels: ✨ Feature

#55 refactor: 상품 문의 컴포넌트 분리 및 연결
  package-lock.json
  package.json
  src/components/index.js
  src/components/product-inquiry/index.html
  src/components/product-inquiry/product-inquiry.js
  src/components/product-inquiry/product-inquiry.scss
  src/pages/product-detail/index.html
  src/pages/product-detail/product-detail.js
  src/pages/product-inquiry/product-inquiry.js
Labels: ⚙ Setting, 🔨 Refactor

#59 bugfix: 모달로 인한 화면 가림 버그 Fix
  src/components/modal/modal.js
  src/components/modal/modal.scss
Labels: 🐞 BugFix

#61 feature: 헤더, 메인페이지, 상세페이지 기능 구현 및 데이터 통신
  src/api/imageUrl.js
  src/components/cart-button/cart-button.js
  src/components/cart-button/cart-button.scss
  src/components/header-small/header-small.js
  src/components/header-small/header-small.scss
  src/components/header/header.js
  src/components/header/header.scss
  src/components/recent-product/recent-product.js
  src/components/recent-product/recent-product.scss
  src/main.js
  src/pages/product-detail/index.html
  src/pages/product-detail/product-detail.js
  src/pages/product-detail/product-detail.scss
  src/utils/cart.js
  src/utils/index.js
Labels: ✨ Feature, 🐞 BugFix, 📬 API

#66 feature: 장바구니 페이지 기능 구현 및 데이터 통신
  public/assets/icons/product-cart/DefaultMinus.svg
  public/assets/icons/product-cart/Delete.svg
  public/assets/icons/product-cart/Minus.svg
  public/assets/icons/product-cart/Plus.svg
  src/components/cart-button/cart-button.js
  src/components/cart-button/cart-button.scss
  src/pages/product-cart/index.html
  src/pages/product-cart/product-cart.js
  src/pages/product-cart/product-cart.scss
  src/pages/product-detail/index.html
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#68 feature: 로그인 페이지 기능 구현
  src/components/modal/modal.js
  src/pages/login/index.html
  src/pages/login/login.js
  src/pages/login/login.scss
Labels: ✨ Feature, 📬 API

#64 feat: 상품 후기 및 문의 기능 구현
  src/components/product-inquiry/index.html
  src/components/product-inquiry/product-inquiry.js
  src/components/product-inquiry/product-inquiry.scss
  src/components/product-review/index.html
  src/components/product-review/product-review.js
  src/components/product-review/product-review.scss
Labels: ✨ Feature, 📬 API

#71 feature: 헤더 로그인에 따른 조건부 렌더링
  src/api/defaultAuthData.js
  src/api/index.js
  src/components/cart-button/cart-button.js
  src/components/header-small/header-small.js
  src/components/header-small/header-small.scss
  src/components/header/header.js
  src/components/header/header.scss
  src/pages/login/index.html
  src/pages/login/login.js
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#72 feat: 상품 목록 렌더링
  public/assets/icons/arrow/category.svg
  src/components/index.js
  src/components/side-filter-panel/side-filter-panel.js
  src/pages/product-list/index.html
  src/pages/product-list/product-list.js
  src/pages/product-list/product-list.scss
Labels: 📬 API, 🔨 Refactor

#75 feat: 회원가입 페이지 기능 구현 및 데이터 통신
  src/pages/register/add-options.js
  src/pages/register/address-search.js
  src/pages/register/agreement-checkboxes.js
  src/pages/register/email-validation.js
  src/pages/register/index.html
  src/pages/register/invite-validation.js
  src/pages/register/name-validation.js
  src/pages/register/password-validation.js
  src/pages/register/register.js
  src/pages/register/register.scss
  src/pages/register/submit-button.js
  src/pages/register/username-validation.js
  src/pages/register/utils.js
Labels: ✨ Feature, 📬 API

#76 feature: 로그인 관련 문의, 후기 관련 기능 수정
  src/components/product-inquiry/index.html
  src/components/product-inquiry/product-inquiry.js
  src/components/product-review/index.html
  src/components/product-review/product-review.js
  src/components/product-review/product-review.scss
  src/components/review-modal/modal.scss
Labels: ✨ Feature, 🐞 BugFix, 📬 API

#79 BigFix: 문의 입력 버튼 비활성화 이슈 해결
  src/components/product-inquiry/product-inquiry.js
Labels: 🐞 BugFix

#82 bugfix: 장바구니 페이지 미로그인시 목록 보이지 않던 현상 수정
  src/pages/product-cart/product-cart.js
Labels: 🐞 BugFix

#83 BugFix: 비밀글 관련 버그 수정
  src/components/product-inquiry/product-inquiry.js
Labels: 🐞 BugFix

#84 refactor: CSS 컨벤션에 맞춰 수정
  index.html
  public/assets/images/banner/banner01.png
  public/assets/images/banner/banner01.webp
  public/assets/images/banner/banner02.png
  public/assets/images/banner/banner02.webp
  public/assets/images/banner/banner03.png
  public/assets/images/banner/banner03.webp
  public/assets/images/banner/banner04.png
  public/assets/images/banner/banner04.webp
  public/assets/images/banner/line-banner01.png
  public/assets/images/banner/line-banner01.webp
  public/assets/images/benefit/benefit01.webp
  public/assets/images/benefit/benefit02.webp
  public/assets/images/benefit/benefit03.webp
  public/assets/images/benefit/benefit04.webp
  public/assets/images/benefit/benefit05.webp
  src/components/ad-popup/ad-popup.scss
  src/components/cart-button/cart-button.js
  src/components/cart-button/cart-button.scss
  src/components/recent-product/recent-product.scss
  src/components/side-filter-panel/side-filter-panel.js
  src/main.js
  src/main.scss
  src/pages/benefit/benefit.js
  src/pages/benefit/benefit.scss
  src/pages/benefit/index.html
  src/pages/product-collection/product-collection.js
  src/pages/product-collection/product-collection.scss
  src/pages/product-list/index.html
  src/pages/product-list/product-list.js
  src/pages/product-list/product-list.scss
  src/styles/abstracts/_variables.scss
  src/styles/base/_reset.scss
Labels: 🔨 Refactor

#87 feature: 상품 문의 좋아요 버튼 구현 및 후기 작성 로직 수정
  src/components/product-review/product-review.js
  src/components/product-review/product-review.scss
Labels: ✨ Feature, 📬 API, 🥰 Accessibility

#89 Docs: README.md 작성
  README.md
Labels: 📃 Docs

#91 feature: 상품 디테일 페이지 재고에 따른 렌더링 처리
  public/assets/icons/product-detail/BellEnable.svg
  src/pages/product-detail/product-detail.js
  src/pages/product-detail/product-detail.scss
Labels: ✨ Feature

#94 Docs: README.md 재수정
  README.md
Labels: 📃 Docs

#95 feat: 샛별배송 페이지 마크업 및 스타일링
  public/assets/images/benefit/benefit01.webp
  public/assets/images/benefit/benefit02.webp
  public/assets/images/benefit/benefit03.webp
  public/assets/images/benefit/benefit04.webp
  public/assets/images/benefit/benefit05.webp
  public/assets/images/delivery/delivery01.webp
  src/components/header/header.js
  src/pages/benefit/benefit.scss
  src/pages/benefit/index.html
  src/pages/delivery/delivery.js
  src/pages/delivery/delivery.scss
  src/pages/delivery/index.html
Labels: 🎨 Html&css

#96 feature: 각 페이지 점검 및 수정
  src/components/cart-button/cart-button.js
  src/components/header-small/header-small.js
  src/components/header/header.js
  src/pages/product-list/product-list.js
  src/pages/register/address-search.js
  src/pages/register/email-validation.js
  src/pages/register/index.html
  src/pages/register/invite-validation.js
  src/pages/register/register.js
  src/pages/register/register.scss
  src/pages/register/submit-button.js
  src/pages/register/username-validation.js
  vite.config.js
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#98 docs: README.md 파일 수정
  README.md
Labels: 📃 Docs

#100 modify: 스와이퍼 슬라이드가 변경될 때마다 alt 속성 업데이트
  README.md
  src/components/side-filter-panel/side-filter-panel.js
  src/main.js
  src/pages/product-list/product-list.js
Labels: 🔨 Refactor, 🥰 Accessibility
